pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/joseh-my-projects/terraform.git'
            }
        }
        stage('Terraform Init/Fmt/Validate') {
            steps {
                echo "Terraform"
            }
        }
        stage('Terraform Plan') {
            steps {
                echo "Plan"
            }
        }
        stage('Confirmation') {
            steps {
                input {
                    message "Press Ok to continue with the deployment."
                }
                echo "Deployment confirmed. Proceeding..."
            }
        }
        stage('Apply') {
            steps {
                echo "Applied"
            }

        }
    }
}