pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/joseh-my-projects/terraform.git'
            }
        }
        stage('Terraform Init/Fmt/Validate') {
            steps {
                sh "terraform init"
                sh "terraform fmt"
                sh "terraform validate"
            }
        }
        stage('Terraform Plan') {
            steps {
                sh "terraform plan"
            }
        }
        stage('Approval') {
            steps {
                input message: "Press Ok to continue with the deployment."
                }
            }
        stage('Apply') {
            steps {
                echo "Applied"
            }
        }
    }
}