pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/joseh-my-projects/terraform.git'
            }
        }
        stage('Terraform Init/Fmt/Validate') {
            steps {
                sh '''
                cd ./ecs-cluster
                terraform init
                terraform fmt
                terraform validate
                terraform plan
                '''
            }
        }
        stage('Approval') {
            steps {
                input message: "Click proceed to continue with the deployment."
                }
            }
        stage('Apply') {
            steps {
                echo "Applied"
            }
        }
    }
}